[package]
name = "remu_feature"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = [ "wenjiu <27843087979@qq.com>" ]

[dependencies]
pest = {workspace = true}
pest_derive = {workspace = true}
