WHITESPACE = _{ " " | "\t" }

cmd = @{ (ASCII_ALPHA | ASCII_DIGIT | "_" | operation)+ }

operation = _{ add | subtract | deref | reg }
    add         = _{ "+" }
    subtract    = _{ "-" }
    deref       = _{ "*" }
    reg         = _{ "$" }

expr = { (ASCII_ALPHA | ASCII_DIGIT | operation)+ }

expr_full = _{ "`" ~ expr ~ "`" }

term = {(cmd | expr_full)+}

term_cell = _{ term | "(" ~ term ~ ")" }

cmd_full = _{ (WHITESPACE)* ~ term_cell* ~ ("&&" ~ term_cell)* }
