[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.'cfg(all(any(target_arch = "riscv32", target_arch = "riscv64"), target_os = "none"))']
linker = "rust-lld"
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tlink.x"]

[target.riscv32i-unknown-none-elf]
runner = "remu_hal/scripts/remu-cargo-runner.sh"

[target.riscv32im-unknown-none-elf]
runner = "remu_hal/scripts/remu-cargo-runner.sh"

[target.riscv32imac-unknown-none-elf]
runner = "remu_hal/scripts/remu-cargo-runner.sh"
