[package]
name = "remu_hal"
version = "0.1.0"
edition = "2024"

[dependencies]
remu_macro = { path = "../../remu_macro" }
remu_hal_macros = { path = "./macros" }
embedded-io = "0.7.1"

[target.'cfg(target_os = "none")'.dependencies]
remu_hal_embedded = { path = "./embedded" }

[target.'cfg(not(target_os = "none"))'.dependencies]
remu_hal_host = { path = "./host" }

[lints]
workspace = true
