#![cfg_attr(target_arch = "riscv32", no_std, no_main)]

//! A minimal Slint UI demo running on remu (embedded) and host.
//!
//! Demonstrates keyboard (global key-pressed callback) and mouse
//! (TouchArea mouse-moved + button click) interaction.

extern crate alloc;

#[allow(unreachable_pub)]
mod ui {
    slint::include_modules!();
}
use ui::MainWindow;

use remu_hal::{FmtWrite, MTIME_TICK_HZ, Uart16550, display_alive, exit_success, read_mtime};
use remu_hal_slint::SlintApp;
use slint::ComponentHandle as _;

/// Slint drives its own redraw when the scene changes; we throttle the input
/// pump / redraw loop to ~60 fps.
const FRAME_MS: u64 = 16;

#[cfg_attr(target_arch = "riscv32", remu_hal::entry)]
fn main() -> ! {
    remu_hal::init();
    let mut uart = Uart16550::default_base();
    let _ = writeln!(uart, "slint: booting");

    // Install the software-renderer platform and create the app handle.
    let mut app = SlintApp::init();

    // Create the UI (generated by slint::include_modules!).
    let ui = MainWindow::new().expect("create MainWindow");
    // Size the Slint window to the full display area (the .slint file leaves
    // the window size up to the runtime so the whole framebuffer is covered).
    ui.window().set_size(slint::PhysicalSize::new(
        remu_hal::read_disp_w().max(1) as u32,
        remu_hal::read_disp_h().max(1) as u32,
    ));

    let t0 = read_mtime();
    let mut last = 0u64;

    loop {
        // Pump input + redraw (Slint renders into the remu framebuffer).
        app.update();

        // Drive the progress bar as a looping animation (0..=100 over ~4s).
        let ms = read_mtime().wrapping_sub(t0) * 1000 / MTIME_TICK_HZ as u64;
        ui.set_progress(((ms / 40) % 101) as i32);

        // Throttle to ~60 fps.
        let mut now = ms;
        while now < last + FRAME_MS {
            now = read_mtime().wrapping_sub(t0) * 1000 / MTIME_TICK_HZ as u64;
        }
        last = now;

        // Detect window close (host: user closes the window; embedded: n/a).
        if !display_alive() {
            let _ = writeln!(uart, "slint: window closed, exiting");
            exit_success();
        }
    }
}
